name: FragmentFPS
version: '${project.version}'
main: xyz.fragmentmc.fragmentfps.FragmentFPS
api-version: 1.20
authors: [ jesus_is_hot ]
description: 1.20.1 Plugin for cannoning fps improvements.
website: fragmentmc.xyz

depend:
  [ ProtocolLib ]

commands:
  fps:
    decription: Open the FPS GUI
    usage: /<command>
    aliases: [ fpssettings, fpsgui ]
    permission: fps.fps
  reload:
    decription: Reload FragmentFPS Config
    usage: /<command>
    aliases: [ ffreload, fragmentfpsreload ]
    permission: fps.reload